apiVersion: v1
kind: Service
metadata:
  name: front-api
spec:
  type: NodePort
  selector:
    app: front-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # nodePort: 30164
