apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: front-api
  template:
    metadata:
      labels:
        app: front-api
    spec:
      containers:
        - name: web
          image: jibranhaseeb/flask-redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
